# Generated by Django 3.2.5 on 2021-07-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_finalamount_saveorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.TextField(default='good restaurant', max_length=5000),
        ),
    ]
