# Generated by Django 3.2 on 2021-07-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='item_description',
            field=models.TextField(default='good item', max_length=5000),
        ),
    ]
