# Generated by Django 3.2 on 2021-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/user_image/default.png', null=True, upload_to='media/user_image/'),
        ),
    ]
