# Generated by Django 3.2.5 on 2021-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cart_user_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_quantity',
            new_name='food_quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='food_total_price',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
