# Generated by Django 3.2 on 2021-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_booktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='restaurant_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
