# Generated by Django 3.2.5 on 2021-07-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210706_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=250)),
                ('alternate_mobile_number', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=250)),
                ('latlong', models.CharField(max_length=250)),
            ],
        ),
    ]
