# Generated by Django 3.2 on 2021-07-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_booktable_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='restaurant_id',
        ),
    ]
