# Generated by Django 3.2 on 2021-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_booktable_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='restaurant_name',
            field=models.CharField(default='shree nath', max_length=500),
        ),
    ]
