# Generated by Django 3.2 on 2021-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_booktable_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='rest_id',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
