# Generated by Django 3.2.5 on 2021-07-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_address_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
