# Generated by Django 3.2.5 on 2021-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_address_landmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latlong',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
