# Generated by Django 3.2.5 on 2021-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order_history_order_id_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_id',
            name='payment_type',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
