# Generated by Django 3.2.5 on 2021-07-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_order_id_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='amount',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
