# Generated by Django 3.2.5 on 2021-07-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_restaurant_description'),
        ('user', '0013_rename_order_id_user_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_order',
            new_name='user_order_item',
        ),
        migrations.RemoveField(
            model_name='order_history',
            name='food_id',
        ),
    ]
