# Generated by Django 3.2.5 on 2021-07-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210707_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_history',
            name='address_id',
        ),
    ]
